### ISSUE TITLE
Does this pass all test cases?

### ISSUE THREAD

**Issue by noahvrz** [bowdoin-cg-spring18/helloworld-jasperhouston#1]
This is a pretty complicated program, and mission critical. Can you write a series of test cases and make sure it all passes?

Further, I don't believe this follows Dick Wilkins' exacting coding standards for C/C++ code.

**Comment by jasperhouston** [comment]
It passes every test case that you are willing to write

**Comment by noahvrz** [comment]
You're right! It passes all the cases!
